### ISSUE TITLE
Open file with...

### ISSUE THREAD

**Issue by Chris2011** [humu2009/candy-pdf-reader#1]
I use windows 7 and when I right click a pdf file and set the option to open file with...to your candy pdf reader, after I double click the pdf, candy opens, but is empty. I think there is missing the pdf as an argument.

Regards

Chris

**Comment by humu2009** [comment]
Oh thanks Chris!  I haven't tested to open a PDF file in that way. I think I need to read node-webkit's document carefully to find out how it works with the shell.

**Comment by Chris2011** [comment]
Anything new here?

**Comment by Chris2011** [comment]
Because of inactivity of this plugin and because I don't use it anymore, I will close this ticket. Thx anyway.
